sudo: false
language: php
php:
  - 5.3
  - 5.6
env:
  - WP_TRAVISCI=travis:phpunit WP_DB_CHARSET=Big5 WP_DB_COLLATION=big5_chinese_ci
  - WP_TRAVISCI=travis:phpunit WP_DB_CHARSET=DEC WP_DB_COLLATION=dec8_swedish_ci
  - WP_TRAVISCI=travis:phpunit WP_DB_CHARSET=DOS WP_DB_COLLATION=cp850_general_ci
  - WP_TRAVISCI=travis:phpunit WP_DB_CHARSET=HP WP_DB_COLLATION=hp8_english_ci
  - WP_TRAVISCI=travis:phpunit WP_DB_CHARSET=KOI8-R WP_DB_COLLATION=koi8r_general_ci
  - WP_TRAVISCI=travis:phpunit WP_DB_CHARSET=cp1252 WP_DB_COLLATION=latin1_swedish_ci
  - WP_TRAVISCI=travis:phpunit WP_DB_CHARSET=ISO WP_DB_COLLATION=latin2_general_ci
  - WP_TRAVISCI=travis:phpunit WP_DB_CHARSET=7bit WP_DB_COLLATION=swe7_swedish_ci
  - WP_TRAVISCI=travis:phpunit WP_DB_CHARSET=US WP_DB_COLLATION=ascii_general_ci
  - WP_TRAVISCI=travis:phpunit WP_DB_CHARSET=EUC-JP WP_DB_COLLATION=ujis_japanese_ci
  - WP_TRAVISCI=travis:phpunit WP_DB_CHARSET=Shift-JIS WP_DB_COLLATION=sjis_japanese_ci
  - WP_TRAVISCI=travis:phpunit WP_DB_CHARSET=ISO WP_DB_COLLATION=hebrew_general_ci
  - WP_TRAVISCI=travis:phpunit WP_DB_CHARSET=TIS620 WP_DB_COLLATION=tis620_thai_ci
  - WP_TRAVISCI=travis:phpunit WP_DB_CHARSET=EUC-KR WP_DB_COLLATION=euckr_korean_ci
  - WP_TRAVISCI=travis:phpunit WP_DB_CHARSET=KOI8-U WP_DB_COLLATION=koi8u_general_ci
  - WP_TRAVISCI=travis:phpunit WP_DB_CHARSET=GB2312 WP_DB_COLLATION=gb2312_chinese_ci
  - WP_TRAVISCI=travis:phpunit WP_DB_CHARSET=ISO WP_DB_COLLATION=greek_general_ci
  - WP_TRAVISCI=travis:phpunit WP_DB_CHARSET=Windows WP_DB_COLLATION=cp1250_general_ci
  - WP_TRAVISCI=travis:phpunit WP_DB_CHARSET=GBK WP_DB_COLLATION=gbk_chinese_ci
  - WP_TRAVISCI=travis:phpunit WP_DB_CHARSET=ISO WP_DB_COLLATION=latin5_turkish_ci
  - WP_TRAVISCI=travis:phpunit WP_DB_CHARSET=ARMSCII-8 WP_DB_COLLATION=armscii8_general_ci
  - WP_TRAVISCI=travis:phpunit WP_DB_CHARSET=UTF-8 WP_DB_COLLATION=utf8_general_ci
  - WP_TRAVISCI=travis:phpunit WP_DB_CHARSET=UCS-2 WP_DB_COLLATION=ucs2_general_ci
  - WP_TRAVISCI=travis:phpunit WP_DB_CHARSET=DOS WP_DB_COLLATION=cp866_general_ci
  - WP_TRAVISCI=travis:phpunit WP_DB_CHARSET=DOS WP_DB_COLLATION=keybcs2_general_ci
  - WP_TRAVISCI=travis:phpunit WP_DB_CHARSET=Mac WP_DB_COLLATION=macce_general_ci
  - WP_TRAVISCI=travis:phpunit WP_DB_CHARSET=Mac WP_DB_COLLATION=macroman_general_ci
  - WP_TRAVISCI=travis:phpunit WP_DB_CHARSET=DOS WP_DB_COLLATION=cp852_general_ci
  - WP_TRAVISCI=travis:phpunit WP_DB_CHARSET=ISO WP_DB_COLLATION=latin7_general_ci
  - WP_TRAVISCI=travis:phpunit WP_DB_CHARSET=UTF-8 WP_DB_COLLATION=utf8mb4_general_ci
  - WP_TRAVISCI=travis:phpunit WP_DB_CHARSET=Windows WP_DB_COLLATION=cp1251_general_ci
  - WP_TRAVISCI=travis:phpunit WP_DB_CHARSET=UTF-16 WP_DB_COLLATION=utf16_general_ci
  - WP_TRAVISCI=travis:phpunit WP_DB_CHARSET=Windows WP_DB_COLLATION=cp1256_general_ci
  - WP_TRAVISCI=travis:phpunit WP_DB_CHARSET=Windows WP_DB_COLLATION=cp1257_general_ci
  - WP_TRAVISCI=travis:phpunit WP_DB_CHARSET=UTF-32 WP_DB_COLLATION=utf32_general_ci
  - WP_TRAVISCI=travis:phpunit WP_DB_CHARSET=Binary WP_DB_COLLATION=binary
  - WP_TRAVISCI=travis:phpunit WP_DB_CHARSET=GEOSTD8 WP_DB_COLLATION=geostd8_general_ci
  - WP_TRAVISCI=travis:phpunit WP_DB_CHARSET=SJIS WP_DB_COLLATION=cp932_japanese_ci
  - WP_TRAVISCI=travis:phpunit WP_DB_CHARSET=UJIS WP_DB_COLLATION=eucjpms_japanese_ci
before_install:
- WP_CORE_DIR=/tmp/wordpress/
- |
  if [[ "$WP_TRAVISCI" == "travis:phpunit" ]]; then
      mysql -e "CREATE DATABASE wordpress_tests;" -uroot
      cp wp-tests-config-sample.php wp-tests-config.php
      sed -i "s/youremptytestdbnamehere/wordpress_tests/" wp-tests-config.php
      sed -i "s/yourusernamehere/travis/" wp-tests-config.php
      sed -i "s/yourpasswordhere//" wp-tests-config.php
      svn checkout https://plugins.svn.wordpress.org/wordpress-importer/trunk tests/phpunit/data/plugins/wordpress-importer
  fi
before_script:
- npm install -g npm
- npm install -g grunt-cli
- npm install
script: grunt $WP_TRAVISCI
notifications:
  slack:
    secure: "ln2sC0yUOMzGGJ9PR56cxafCO2YSBQtFs0JuoSjvmXN0+jCGbQL781z2osEJ24BEl4o3zMLfiFPgieM7D+VuRObU6TiVFLmbebgoSyW/1Gs+jPNxBXPKOSLE3/4CV8ifyhm5XZr2xT6z8OWC6StHl2nPis4wZ91UHbj6FhlMyFM="
